$
Name = Salar Ahmed\\
Roll Numer = 19i-1716\\
Class = BS(DS)\\
Section = N\\
$

In [ ]:
import numpy as np
import numpy.linalg as la

## Finding PageRank
![PageRank.png](attachment:PageRank.png)

In [ ]:
#making matrix  A    B    C    D    E    F    U1    U2   U3   U4   U5
P  = np.array([[0   ,0   ,0   ,1/11,0   ,0   ,0   ,0   ,0   ,0   ,0   ],      #A
               [0   ,0   ,1/11,1/11,1/11,1/11,1/11,1/11,1/11,0   ,0   ],      #B
               [0   ,1/11,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ],      #C
               [0   ,0   ,0   ,0   ,1/11,0   ,0   ,0   ,0   ,0   ,0   ],      #D
               [0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ],      #E
               [0   ,0   ,0   ,0   ,1/11,1/11,0   ,0   ,0   ,0   ,0   ],      #F
               [0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ],      #un-named 1
               [0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ],      #un-named 2
               [0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ],      #un-named 3
               [0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ,0   ],      #un-named 4
               [0   ,0   ,0   ,0   ,0   ,0   ,1/11,1/11,1/11,1/11,1/11],])    #un-named 5


$
\textrm{A = 3.3% }\\
\textrm{B = 38.4%}\\
\textrm{C = 34.3%}\\
\textrm{D = 3.9%}\\
\textrm{E = 8.1%}\\
\textrm{unnamed pages = 1.6% , 1.6% , 1.6% , 1.6% , 1.6%}\\
\textrm{F = 3.9%}\\
$


In [ ]:
#making matrix
v  = np.array([[1/11],      #A
               [1/11],      #B
               [1/11],      #C
               [1/11],      #D
               [1/11],      #E
               [1/11],      #F
               [1/11],      #un-named 1
               [1/11],      #un-named 2
               [1/11],      #un-named 3
               [1/11],      #un-named 4
               [1/11],])    #un-named 5

In [ ]:
eigVal,eigVec = la.eig(P)
eigVal
order = np.absolute(eigVal).argsort()[::-1]
order

array([ 6,  4,  1,  0, 10,  9,  8,  7,  5,  3,  2], dtype=int64)

In [ ]:
eigVal = eigVal[order]
eigVec  = eigVec[:,order]
eigVal

array([ 0.        ,  0.        ,  0.09090909,  0.09090909,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.09090909,
       -0.09090909])

In [ ]:
r = eigVec[:, 0]
100 * np.real(r / np.sum(r))
r

array([-1.00000000e+000, -7.54586948e-309, -1.21252186e-290,
        1.21252186e-290,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000])

In [ ]:
eigVec

array([[ 0.00000000e+000,  0.00000000e+000,  1.00000000e+000,
        -1.00000000e+000,  0.00000000e+000,  1.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 7.07106781e-001,  7.07106781e-001,  0.00000000e+000,
        -7.54586948e-309, -7.07106781e-001,  4.42022445e-307,
         0.00000000e+000, -3.59301546e-019, -3.59301546e-019,
        -3.59301546e-019,  0.00000000e+000],
       [ 7.07106781e-001, -7.07106781e-001,  0.00000000e+000,
        -1.21252186e-290, -7.07106781e-001,  1.21252186e-290,
         0.00000000e+000, -5.77350269e-001, -5.77350269e-001,
        -5.77350269e-001,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         1.21252186e-290,  0.00000000e+000, -1.21252186e-290,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.000

In [ ]:
# @ is dot product operator
M = P @ v
M

array([[0.00826446],
       [0.05785124],
       [0.00826446],
       [0.00826446],
       [0.        ],
       [0.01652893],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.04132231]])

In [ ]:
r = 100 * np.ones(11)
for i in np.arange(100):
    r = P @ r
r

array([0.00000000e+000, 7.40170302e-101, 7.61940017e-101, 0.00000000e+000,
       0.00000000e+000, 1.45131432e-102, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 3.62828580e-102])

### above giving weird values because of dead end

formulae for dead ends

$$
P = \frac{1-\beta}{N} + \beta(\frac{PageRank_{prev}(A)}{outlink(A)} + \frac{PageRank_{prev}(B)}{outlink(B)} + \cdots)
$$

$ where, \ \beta= 0.15 $

In [ ]:
beta = 0.15 # We can change this value
# if we increase the value, the convergence decreses
M = beta * P + (1-beta)/11 * np.ones([11, 11])

In [ ]:
r = 100 * np.ones(11) / 11
lastR = r
r = M @ r
i = 0
while la.norm(lastR - r) > 0.01 :
    lastR = r
    r = M @ r
    i += 1
print(str(i) + " iterations to convergence.")
r

44 iterations to convergence.


array([0.0179595 , 0.01963388, 0.01798578, 0.01795517, 0.01767837,
       0.01824077, 0.01767837, 0.01767837, 0.01767837, 0.01767837,
       0.01908435])

# miscellaneous

In [ ]:
1-0.15

0.85

In [ ]:
a= 3.3/100
b= 38.4/100
c= 34.3/100
d= 3.9/100
e= 8.1/100
f= 3.9/100
h= 1.6/100

print(a,b,c,d,e,f,h,h,h,h, sep='\n')

0.033
0.384
0.34299999999999997
0.039
0.081
0.039
0.016
0.016
0.016
0.016


In [ ]:
1/11

0.09090909090909091